source/includes/harvest/_candidates.md
There's a stray `<<< HEAD` comment that needs to be removed from our API docs.
=> Removes a merge conflict from the API Harvest docs

source/includes/assessment/_list_tests.md
According to the documentation for the `list_tests` endpoint, it's a `GET` request, not a `POST`.
=> GET request instead of POST (list_tests)

source/includes/harvest/_candidates.md
Addressing Issue - https://github.com/grnhse/greenhouse-api-docs/issues/73
The prospect endpoint does not reference the application object, which is used to attach prospects to jobs.
=> GREEN-8697/fix prospect docs.

source/includes/job-board/_applications.md
I've recently tried to implement the API job submission using the documentation but failed, since it didn't point out the correct URL and that the Authorization token needed to be base64 encoded.
Maybe it should be added a reference to the packages already developed for this? e.g. https://github.com/grnhse/greenhouse-tools-php
=> Fixed documentation regarding the Job Application Submission

source/includes/harvest/_offers.md
Adds 3 optional filters to `GET /v1/offers/`
resolved_after: list offers resolved after this date
resolved_before: list offers resolved before this date
status: one of ["UNRESOLVED", "ACCEPTED", "REJECTED", "DEPRECATED"]
=> GREEN-13225: Add new offer filters

source/includes/harvest/_job_posts.md
- Adds the `active` field to the Job Post resource which indicates whether or not the job post has been soft-deleted.
```json
{
"id": 278994,
"active": true,  <-- 𝙉𝙀𝙒!!
"live": true,
"title": "Software Engineer, Full Stack",
"location": {
"name": "San Francisco, California"
},
"internal": true,
"external": false,
"job_id": 2769,
"content": null,
"updated_at": "2017-11-22T22:12:00.912Z",
"internal_content": "",
"created_at": "2016-09-09T13:52:02.845Z",
"questions": [
{
"required": true,
"private": false,
"label": "First Name",
"name": "first_name",
"type": "short_text",
"values": [],
"description": null
},
{
"required": true,
"private": false,
"label": "Last Name",
"name": "last_name",
"type": "short_text",
"values": [],
"description": null
}
]
}
```
- Adds the `?active=(true|false)` …
=> GREEN-13532: add job post active field and filter

source/includes/webhooks/_application_events.md, source/includes/webhooks/_candidate_events.md, source/includes/webhooks/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-14595
In addition to adding `employee_id` to the `credited_to` object, we also add it to `coordinator` and `recruiter`.
=> Green 13672 employee id in candidate hired webhook

source/candidate-ingestion.md
It has existed for a while but we aren't showing it
=> Documentation for listing Pools/Stages in Ingestion API

source/includes/harvest/_job_stages.md
Docs to reflect changes to `GET /v1/job_stages/` made in Harvest GREEN-17606. PR: https://github.com/grnhse/api/pull/466
=> Added docs for "schedulable" field in job stages endpoints

source/includes/harvest/_introduction.md, source/includes/harvest/_job_stages.md
Same changes as this PR: https://github.com/grnhse/greenhouse-api-docs/pull/303
Deployed before Harvest was update in prod, so had to revert.
Waiting to deploy now until Harvest endpoints are deployed.
=> Added "schedulable" to job_stages docs

source/includes/harvest/_candidates.md
All the education fields are now not required and there are four new
fields: start_month, start_year, end_month, end_year
https://greenhouseio.atlassian.net/browse/GREEN-18218
=> Updated education for harvest api

Gemfile, Gemfile.lock
Package upgrade to be compatible with Ruby 2.4.5.
- json: 1.8.3 -> 1.8.6
- rubyracer: 0.12.2 -> 0.12.3
- ref: 1.0.5 -> 2.0.0
- libv8: 3.16.14.0 -> 3.16.14.15
- bundler: 1.16.1 -> 1.17.3
=> Upgrade json

source/includes/harvest/_introduction.md
Warn users to not rely on document links to be available forever.
=> Warn about expiring links.

Dockerfile
Using the Ruby:2.5.1 image causes the following error:
Step 7/11 : RUN bundle install
---> Running in 2faa8f2f9af0
You must use Bundler 2 or greater with this lockfile.
The command '/bin/sh -c bundle install' returned a non-zero code: 20
Upgrading it to Ruby:2.6 makes it work properly.
=> Upgrading Ruby-image to fix error

source/includes/harvest/_applications.md
fixed typo for prospective_department and prospective_office having the wrong definitions assigned to them
[GREEN-30828](https://greenhouseio.atlassian.net/browse/GREEN-30828)
=> [GREEN-30828] - bug fixed typo on applications page

source/includes/harvest/_applications.md
I believe you have prospective_office and prospective_department referring to each other in your table.
=> Fix typo in _applications.md

source/includes/harvest/_applications.md
I encountered a small typo in the POST: Reject Application documentation:
rejection_email.email_template_id    The template **the** to use for the rejection email.
=> Minor typo in _applications.md

source/includes/harvest/_applications.md
Application can have a status of `converted`, as seen here:
However, the noteworthy attributes section is missing the `converted` status:
=> Application missing `converted` status in noteworthy attributes section in docs

source/includes/gho/_api.md
added examples for the following mutations:
- addDepartment
- addLocation
- updateDepartment
- updateLocation
- deleteDepartment
- deleteLocation
added examples for the following queries:
- complexityInfo
- contactRelationships
- countries
- customField
- customFields
- department
- departments
- employee (missing fields)
- employees (missing filters)
- employmentStatuses
- locations
- otherCriteria
- otherCriterion
- rateLimit
- team
- teamCategory
- teamCategories
- teams
some miscellaneous fixes:
- `name` is Required for AddDepartmentInput
- `name` is Required for AddLocationInput
=> ON-5279: Add Missing Examples in Queries and Mutations

source/includes/webhooks/_introduction.md
Add example of compensation field to custom fields web hooks documentation
=> Update docs to include compensation fields

source/includes/assessment/_introduction.md, source/includes/assessment/_send_test.md
=> Add sent_by to assessment api's send_test request example

source/includes/webhooks/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-52125
=> GREEN-52125: Update webhook retry policy

source/includes/job-board/_applications.md, source/includes/job-board/_jobs.md
=> [GREEN-53503] Update Job Board API docs to include `gdpr_demographic_data_consent_given` field
