grnhse/greenhouse-api-docs

- source/includes/harvest/_job_posts.md
- source/includes/job-board/_applications.md
Update docs to reflect work being done to support internal job board integration.
> Add internal job board support

- source/includes/job-board/_applications.md
- source/includes/job-board/_departments.md
- source/includes/job-board/_introduction.md
- source/includes/job-board/_jobs.md
- source/includes/job-board/_offices.md
- source/job-board.md
https://greenhouseio.atlassian.net/browse/GREEN-4894
> Green 4894 jobs api is tiered

- source/includes/harvest/_job_stages.md
Expose Interview Kit IDs in the Job Stage resource
> Add job stages interview kit IDs

- source/includes/harvest/_departments.md
- source/includes/harvest/_offices.md
https://greenhouseio.atlassian.net/browse/GREEN-4955
> Added harvest documentation for tiered offices and departments

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-5567
> Add documentation for Appliction Unreject Endpoint

- source/includes/harvest/_jobs.md
https://greenhouseio.atlassian.net/browse/GREEN-6183
> Docs for patch job

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-6266
> GREEN-6266/get includes custom fields

- source/includes/harvest/_jobs.md
https://greenhouseio.atlassian.net/browse/GREEN-6310
> Fix requisition id type typo

- source/includes/harvest/_candidates.md
Adds description on how to patch custom fields in to the candidate doc.
> Green 6287 patch candidate custom field doc

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-6196
> Add patch application docs

- source/includes/harvest/_candidates.md
https://greenhouseio.atlassian.net/browse/GREEN-6336
> GREEN-6336/Make POST application request more consistent

- source/includes/harvest/_users.md
https://greenhouseio.atlassian.net/browse/GREEN-6135
> Add employee id to json objects for user

- source/harvest.md
- source/includes/harvest/_tags.md
Docs for the new candidate tag end points
> Candidate tags docs

- source/harvest.md
- source/includes/harvest/_tags.md
https://greenhouseio.atlassian.net/browse/GREEN-6547
> Updated candidate tag docs

- source/includes/webhooks/_application_deleted.md
- source/webhooks.md
Application deleted web hook documentation.
> GREEN-6532_application_deleted_docs

- source/includes/harvest/_scorecards.md
Adds `application_id` to scorecards doc.
> GREEN-6541/Application ID in scorecards.

- source/includes/webhooks/_offer_deleted.md
- source/webhooks.md
> GREEN-6531_Offer_deleted_docs.

- source/includes/harvest/_candidates.md
https://greenhouseio.atlassian.net/browse/GREEN-6523
> GREEN-6523/Delete candidate docs

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-6524
> GREEN-6524/Delete application docs

- source/includes/webhooks/_job_created.md
- source/includes/webhooks/_job_updated.md
- source/webhooks.md
https://greenhouseio.atlassian.net/browse/GREEN-6527
> GREEN-6527/Job Updated web hook docs

- source/includes/webhooks/_candidate_deleted.md
- source/webhooks.md
The delete candidate web hook docs
> GREEN-6542/Candidate deleted docs.

- source/includes/harvest/_candidates.md
https://greenhouseio.atlassian.net/browse/GREEN-6529
> GREEN-6529/Post candidate docs

- source/includes/harvest/_tags.md
https://greenhouseio.atlassian.net/browse/GREEN-6525
https://greenhouseio.atlassian.net/browse/GREEN-6526
> GREEN-6525/6-Update candidate tag docs

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-6522
> GREEN-6522/Change move application description

- source/includes/harvest/_candidates.md
https://greenhouseio.atlassian.net/browse/GREEN-6530
> GREEN-6530/Post prospect docs

- source/includes/webhooks/_scorecard_deleted.md
- source/webhooks.md
https://greenhouseio.atlassian.net/browse/GREEN-6648
> GREEN-6648/Scorecard deleted webhook docs

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-6711
> Change correct Application doc

- source/includes/webhooks/_application_updated.md
- source/webhooks.md
https://greenhouseio.atlassian.net/browse/GREEN-6409
> GREEN-6409/Add application updated webhook docs

- source/includes/webhooks/_application_deleted.md
- source/includes/webhooks/_candidate_deleted.md
- source/includes/webhooks/_candidate_stage_change.md
- source/includes/webhooks/_hire_candidate.md
- source/includes/webhooks/_job_created.md
- source/includes/webhooks/_new_candidate_application.md
- source/includes/webhooks/_new_prospect_application.md
- source/includes/webhooks/_offer_deleted.md
- source/includes/webhooks/_reject_candidate.md
- source/includes/webhooks/_update_candidate.md
https://greenhouseio.atlassian.net/browse/GREEN-6765
> Update Web Hook payloads

- source/includes/harvest/_applications.md
- source/includes/harvest/_candidates.md
- source/includes/harvest/_jobs.md
- source/includes/harvest/_offers.md
Add keyed custom fields to documentation.
> Add keyed custom fields to docs.

- source/includes/webhooks/_interview_deleted.md
- source/webhooks.md
https://greenhouseio.atlassian.net/browse/GREEN-6714
> GREEN-6714/Interview deleted web hook docs

- source/includes/harvest/_eeoc.md
- source/includes/harvest/_introduction.md
Documentation: GET: List EEOC Data
> Documentation: GET: List EEOC Data

- source/includes/harvest/_activity_feed.md
- source/includes/harvest/_candidates.md
Notes a typo in the JSON response and includes the correct one.
> GREEN-7309_Visibility.

- source/includes/webhooks/_unhire_candidate.md
- source/webhooks.md
Docs for when candidate is unhired.
> Green 7308 unhire webhook

- source/includes/webhooks/_hire_candidate.md
- source/includes/webhooks/_job_created.md
- source/includes/webhooks/_job_updated.md
Adds the hiring team to the job web hooks.
> Green 7441 hiring team web hook docs

- source/includes/harvest/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-7417
> GREEN-7417/Fix move application docs

- source/includes/harvest/_departments.md
Docs for creating a new department via harvest.
> Docs for POST department

- source/includes/job-board/_degrees.md
- source/includes/job-board/_disciplines.md
- source/includes/job-board/_schools.md
- source/job-board.md
https://greenhouseio.atlassian.net/browse/GREEN-7298
> add docs for school, degree and discipline

- source/includes/harvest/_applications.md
Fixes incorrect info in the documentation.
> Update reject application to fix typo and change required fields.

- source/includes/webhooks/_candidate_events.md
Docs for the new candidate merged web hook.
> Green 8615 merged candidate webhook docs

- source/includes/harvest/_introduction.md
Addressing Issue https://github.com/grnhse/greenhouse-api-docs/issues/61
Document where one gets an API key in greenhouse.
> GREEN-8698/describe where one gets harvest api keys.

- source/includes/harvest/_jobs.md
- source/includes/harvest/_users.md
> GREEN-8518/docs for posting jobs via harvest.

- source/includes/harvest/_jobs.md
Docs for updating the hiring team.
> Green 8521/hiring team docs

- source/includes/harvest/_job_posts.md
Docs for flipping live/online on job posts.
> GREEN-8523/update job post docs.

- source/includes/harvest/_applications.md
Clarifies changing an application stage on the current job vs new job.
> Add transfer to job endpoint.

- source/includes/harvest/_jobs.md
Can now update office_ids through patch jobs.
> Add office ids as updatable

- source/harvest.md
- source/includes/harvest/_custom_fields.md
- source/includes/harvest/_introduction.md
Docs for the new custom field GET endpoints.
> GREEN-9159/custom field endpoint doc.

- source/includes/harvest/_custom_fields.md
> Green 9508 delete custom field options

- source/includes/harvest/_users.md
Docs for the patch user endpoint.
> Docs for patch user.

- source/includes/candidate-ingestion/_candidates.md
- source/includes/candidate-ingestion/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-9604
Please do not merge this until CRM is launched
> Add warnings about new prospects feature flag

- source/includes/harvest/_candidates.md
https://greenhouseio.atlassian.net/browse/GREEN-9911
Please do not merge this PR until CRM is launched.
> Update docs - crm is required to access add prospects

- source/includes/webhooks/_application_events.md
- source/includes/webhooks/_introduction.md
Please do not merge this until pools and stages in webhooks is released.
> Add prospect owner, pool, and stage to webhooks

- source/includes/job-board/_applications.md
https://greenhouseio.atlassian.net/browse/GREEN-10305
> Adding EEOC and Job Post Examples to API Docs

- source/includes/harvest/_job_openings.md
- source/includes/harvest/_jobs.md
Adds close reason to openings.
> Adds close reasons to job openings.

- source/includes/candidate-ingestion/_candidates.md
- source/includes/candidate-ingestion/_prospect_pools.md
https://greenhouseio.atlassian.net/browse/GREEN-10399
> GREEN-update-docs-with-prospect-pool-related-changes

- source/includes/candidate-ingestion/_candidates.md
- source/includes/candidate-ingestion/_prospect_pools.md
https://greenhouseio.atlassian.net/browse/GREEN-10399
> Move stages copy to the right place

- source/includes/harvest/_scorecards.md
[Jira issue](https://greenhouseio.atlassian.net/browse/GREEN-10819)
> GREEN-10819 Adding more scorecard question examples

- source/includes/harvest/_education.md
- source/includes/harvest/_users.md
Found these two typos while testing some newer endpoints this morning
> Murph typo fixes

- source/includes/harvest/_candidates.md
employments on post candidate/prospect is not live yet, just adding new ones.
> rollback employment from post candidate. merged too soon.

- source/includes/gho/_introduction.md
https://greenhouseio.atlassian.net/browse/ON-2270
> Add documentation for rate limiting the GHO API

- source/includes/harvest/_candidates.md
Adds post e-mail  note.
The associated PR also fixed the "Resource Not In Follower" issue for posting notes.
> Adds post e-mail note.

- source/includes/webhooks/_application_events.md
Missing comma makes this JSON invalid. pls merge, tks!
> update missing comma in new_candidate_application

- source/includes/webhooks/_candidate_events.md
Having an integer of 00000 is not valid in JSON.
> external_id should be 12345 or "00000", not 00000

- source/includes/gho/_introduction.md
https://greenhouseio.atlassian.net/browse/ON-2326
> Fix curl command

- source/includes/gho/_api.md
assorted updates for the release on Monday
> various updates for v1 release

- source/index.html.erb
- source/stylesheets/home.css.scss
https://greenhouseio.atlassian.net/browse/ON-2351
> Add tile for GHO

- source/includes/gho/_introduction.md
We say task is a thing the API can update and query
> updating intro to remove task

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-2460
Updating GHO API examples
> updating gho api examples

- source/includes/harvest/_job_posts.md
New docs for patch job post and get single job post.
> Update job post docs.

- source/includes/gho/_api.md
- source/includes/gho/_introduction.md
https://greenhouseio.atlassian.net/browse/ON-2490
> updating onboarding api docs to reflect new arguments for the employees query

- source/includes/gho/_introduction.md
GraphQL Basic Request description & query example for requesting an email address by employee ID
> adding new intro section for gho api docs

- source/includes/gho/_introduction.md
> fixing link

- source/includes/harvest/_applications.md
Includes docs updates for:
- GET application by status.
- POST hire application
> Green 13092 hire application docs

- source/includes/gho/_introduction.md
Adding documentation for m`maximum complexity`
> Add complexity docs to gho 2

- source/includes/harvest/_user_permissions.md
external ids on future permissions.
> adds external ids.

- source/includes/harvest/_candidates.md
- source/includes/webhooks/_candidate_events.md
https://greenhouseio.atlassian.net/browse/GREEN-13563
> Updating docs with LinkedIn GDPR parameter

- source/includes/gho/_api.md
department and location mutations (add/update/delete)
> add gho foundational data mutations docs

- source/includes/harvest/_offers.md
https://greenhouseio.atlassian.net/browse/GREEN-14545
> add sent_after and sent_before Offer filters to docs.

- source/includes/harvest/_departments.md
- source/includes/harvest/_eeoc.md
- source/includes/harvest/_offices.md
- source/includes/harvest/_users.md
https://greenhouseio.atlassian.net/browse/GREEN-15265
> GREEN-15265 API Copy Changes

- source/includes/harvest/_introduction.md
Adds Harvest Change Logs to Intro section
> First new change logs

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-3180
> Update documentation to have GHR IDs, Team External IDs, etc.

- source/includes/job-board/_jobs.md
https://greenhouseio.atlassian.net/browse/GREEN-16195
> Adding requisition ID to the docs

- source/includes/webhooks/_introduction.md
Clarification from https://github.com/grnhse/greenhouse-api-docs/issues/276
> Web hook unicode note.

- source/layouts/home.erb
https://greenhouseio.atlassian.net/browse/CULT-286
> Update engineering blog link

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
For this:
https://github.com/grnhse/greenhouse/pull/9250
> Add info about PATCHing prospect pool data

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
This reverts commit 8c00b9b5938bb181b6d356711b208b5769c9fad6, reversing
changes made to 644c89117dda19fdce914ccc873077c6c79dde94.
> Rollback GREEN-16402

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
Redo of https://github.com/grnhse/greenhouse-api-docs/pull/296
> Green 16402 patch crm

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_posts.md
https://greenhouseio.atlassian.net/browse/GREEN-17165
> Added ability for job post location for office and custom locations

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_stages.md
https://greenhouseio.atlassian.net/browse/GREEN-17771
> Add estimated time, default interviewers to stages

- source/includes/webhooks/_application_events.md
- source/includes/webhooks/_introduction.md
Adds employee id to user custom fields.
Adds a description of custom field values to the intro.
> custom field value documentation.

- source/includes/harvest/_departments.md
- source/includes/harvest/_offices.md
Adds external ids to parent and children offices and departments.
> Docs for external ids for parents and children.

- source/includes/harvest/_applications.md
- source/includes/harvest/_candidates.md
- source/includes/harvest/_introduction.md
Corresponds to these PRs
https://github.com/grnhse/greenhouse/pull/9498
https://github.com/grnhse/api/pull/472
> Added docs for POST Attachments to Application endpoint

- source/includes/assessment/_patch_completed_test.md
- source/includes/assessment/_send_test.md
- source/includes/assessment/_test_status.md
https://greenhouseio.atlassian.net/browse/GREEN-17735
> Add docs for PATCH Completed Test option

- source/assessment.md
- source/includes/assessment/_patch_completed_test.md
- source/includes/assessment/_send_test.md
- source/includes/assessment/_test_status.md
https://greenhouseio.atlassian.net/browse/GREEN-19177
> Adding PATCH Completed Test and links

- source/includes/job-board/_sections.md
- source/job-board.md
https://greenhouseio.atlassian.net/browse/GREEN-18335
> Add job board section docs

- source/includes/assessment/_patch_completed_test.md
https://greenhouseio.atlassian.net/browse/GREEN-19606
> Fix formatting for PATCH completed test

- source/includes/job-board/_jobs.md
- source/includes/job-board/_sections.md
https://greenhouseio.atlassian.net/browse/GREEN-19443
> Update Job Board API documentation for Prospect Posts

- source/includes/harvest/_job_posts.md
https://greenhouseio.atlassian.net/browse/GREEN-19819
> Update examples for job post location field

- Dockerfile
- README.md
Copied from https://github.com/slatedocs/slate/wiki/Docker
https://greenhouseio.atlassian.net/browse/GREEN-20414
> Update Dockerfile and instructions

- source/includes/webhooks/_job_events.md
https://greenhouseio.atlassian.net/browse/GREEN-18553
> GREEN-18553 Clarifying prospect vs job post

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_openings.md
Docs for https://greenhouseio.atlassian.net/browse/GREEN-20120
> GREEN-20943 Added custom fields to POST Openings docs

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_openings.md
https://greenhouseio.atlassian.net/browse/GREEN-20944
> Docs for PATCH opening updates

- source/includes/harvest/_introduction.md
Reopening closed branch to update change log times
> GREEN-19843-2 Update change log times

- source/includes/harvest/_users.md
This change was sparked by this thread from @mschmaus201.
https://greenhouse-io.slack.com/archives/GHABW7BFY/p1580417974073100
> Clarify the behavior for email and employee_id param

- source/includes/harvest/_custom_fields.md
Relevant change to Harvest: https://github.com/grnhse/api/pull/516
> Add CF Option external_id / description

- source/includes/job-board/_introduction.md
Jira Card: https://greenhouseio.atlassian.net/browse/GREEN-22119
Changed "https://api.greenhouse.io/v1/example/method/url?callback="
to "https://boards-api.greenhouse.io/v1/example/method/url?callback="
> Add boards to Callback URL

- source/includes/harvest/_introduction.md
- source/includes/harvest/_scorecards.md
https://greenhouseio.atlassian.net/browse/GREEN-23704
> Adds interview_step to the scorecards response.

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-3752
> ON-3752 Add createdAt filter for querying GHO employees

- source/includes/harvest/_custom_fields.md
- source/javascripts/app/_search.js
Adds POST custom_fields documentation
BONUS: Added a debounce onto the search bar so that the search bar doesn't freeze up when you type the first letter.
> Green 24589 create custom fields

- source/includes/harvest/_custom_fields.md
Docs for create custom fields.
> adds custom field creation info.

- source/includes/harvest/_custom_fields.md
- fix formatting for POST custom fields, add request URL
- add description field to POST custom fields
- add PATCH custom field endpoint docs
- add description to DELETE custom field
> GREEN-24939: Add PATCH custom fields

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_posts.md
- source/includes/job-board/_jobs.md
https://greenhouseio.atlassian.net/browse/GREEN-25127
> Updating docs for Standardized Descriptions

- source/includes/candidate-ingestion/_introduction.md
- source/includes/harvest/_users.md
Hi @liamkillion,
I have included the JSON to PATCH Enable User to match what is shown in the Disable user example. Also re ordered the endpoint for disable user so it follows the structure, http endpoint then headers similar to the rest of the doc. This is related to trello card: https://trello.com/c/6spM6JW7/81-update-patch-enable-user-page-to-instruct-users-to-follow-disable-user-format-instructions.
> Update patch enable user json

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-4575
> Update employmentStatuses endpoint to return a list of strings

- source/includes/harvest/_demographic_data.md
https://greenhouseio.atlassian.net/browse/GREEN-26810
> Adds answer types to demographic questions

- source/includes/gho/_api.md
> Add an example for terminating GHO employee

- source/includes/harvest/_users.md
JIRA card https://greenhouseio.atlassian.net/browse/GREEN-28494
And here's what it looks like
> Add PATCH user permission level docs

- README.md
- source/includes/candidate-ingestion/_candidates.md
- source/includes/candidate-ingestion/_current_user.md
- source/includes/candidate-ingestion/_jobs.md
- source/includes/candidate-ingestion/_prospect_pools.md
- source/includes/candidate-ingestion/_tracking_link.md
https://greenhouseio.atlassian.net/browse/GREEN-28712
related GHR card https://greenhouseio.atlassian.net/browse/GREEN-28505
> Update Ingestion API get current user docs

- source/includes/harvest/_custom_fields.md
- source/includes/harvest/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-28739
> Add external_id examples to custom field options

- source/includes/harvest/_eeoc.md
https://greenhouseio.atlassian.net/browse/GREEN-24412
> Update EEOC copy

- source/includes/harvest/_applications.md
- source/includes/harvest/_candidates.md
- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_stages.md
https://greenhouseio.atlassian.net/browse/GREEN-28903
> Add job_post_id to application response object

- source/includes/harvest/_introduction.md
- source/includes/harvest/_scheduled_interviews.md
https://greenhouseio.atlassian.net/browse/GREEN-29176
> Add video_conferencing_url to Scheduled Interviews

- source/includes/candidate-ingestion/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-29583
> Delete docs about omniauth

- source/includes/job-board/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-29580
> Delete doc about libraries from job board api

- source/includes/webhooks/_introduction.md
with changes from https://greenhouseio.atlassian.net/browse/GREEN-30096, we should update the docs to say retry of 12 times to reflect the changes. Here's what I'm updating to (verbiage copied from https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry):
> Update webhook retry docs

- source/includes/gho/_api.md
- source/includes/gho/_introduction.md
https://greenhouseio.atlassian.net/browse/ON-4917
> On 4917 non deletable field type functionality

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-3871
> ON-3781: Mark email required in AddPendingHireInput

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-5217
> ON-5217: Remove deprecated employees query arguments

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_openings.md
Documentation for the new v2 delete openings endpoint.
> Add docs for new v2 endpoint

- source/includes/harvest/_custom_fields.md
- source/includes/harvest/_introduction.md
- source/includes/harvest/_jobs.md
- source/includes/harvest/_users.md
https://greenhouseio.atlassian.net/browse/GREEN-32758
> Add User Attributes

- source/includes/harvest/_job_posts.md
- source/includes/job-board/_jobs.md
This is updating docs for these changes: https://github.com/grnhse/jben/pull/1050
> GREEN-37301: Add pay transparency query param to jben job post request docs

- source/includes/harvest/_candidates.md
- source/includes/webhooks/_introduction.md
public and admin_only are not valid attachment types
https://greenhouseio.atlassian.net/browse/GREEN-38181
> GREEN-38181 Update api docs to reflect reality

- source/includes/harvest/_job_posts.md
> Green-39797: Add internal param

- source/includes/harvest/_introduction.md
- source/includes/harvest/_scheduled_interviews.md
> Scheduled interviews doc fix format

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_openings.md
Link to JIRA: https://greenhouseio.atlassian.net/browse/GREEN-41695
> GREEN-41695 - Harvest PATCH openings: update documentation

- source/includes/job-board/_applications.md
- source/includes/job-board/_jobs.md
https://greenhouseio.atlassian.net/browse/GREEN-39061
> [GREEN-39061] Update Job Board API docs to use separate consent decisions for applications

- source/includes/assessment/_introduction.md
[GREEN-44903]
[GREEN-44903]: https://greenhouseio.atlassian.net/browse/GREEN-44903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GREEN-44903: Update Assessment API Docs

- source/includes/audit-log/_introduction.md
> GREEN-43519 Update Audit log pagination documentation

- source/includes/audit-log/_introduction.md
GREEN-43530-update-audit-log-rate-limiting-api-documentation
> GREEN-43530-update-audit-log-rate-limiting-api-documentation

- source/includes/harvest/_introduction.md
> Update error message

- source/includes/harvest/_introduction.md
- source/includes/harvest/_job_posts.md
> Green 44007 add job post custom location id to harvest documentation

- source/includes/gho/_pagination.md
https://greenhouseio.atlassian.net/browse/ON-6545
> ON-6545 include max number of records in pagination copy

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-6567
> Add assignedTaskName field to Document

- source/includes/gho/_api.md
https://greenhouseio.atlassian.net/browse/ON-6637
> On 6637 add signature request form fields type

- source/includes/gho/_api.md
> Fix link and brackets

- source/includes/harvest/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-48423
> Green 48423 Update Harvest API Throttling Description

- source/includes/harvest/_candidates.md
- source/includes/harvest/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-48148
> Green 48148 Update Harvest API GET:List Candidates documentation

- source/includes/harvest/_introduction.md
- source/includes/harvest/_offices.md
https://greenhouseio.atlassian.net/browse/GREEN-46436
> GREEN-46436 Update List and Retrieve Offices documentation

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-50428
> GREEN-50428: Update Post Reject Application parameter description

- source/includes/harvest/_applications.md
- source/includes/harvest/_introduction.md
https://greenhouseio.atlassian.net/browse/GREEN-51034
Extending off of: https://github.com/grnhse/greenhouse/pull/23181
> Accept rejection_details through PATCH application

- source/assessment.html.md
- source/audit-log.html.md
- source/candidate-ingestion.html.md
- source/gho.html.md
- source/harvest.html.md
- source/includes/harvest/_introduction.md
- source/includes/harvest/_jobs.md
- source/includes/webhooks/_application_events.md
- source/includes/webhooks/_candidate_events.md
- source/includes/webhooks/_interview_events.md
- source/includes/webhooks/_introduction.md
- source/includes/webhooks/_job_events.md
- source/includes/webhooks/_organization_events.md
- source/index.html.md
- source/job-board.html.md
- source/webhooks.html.md
https://greenhouseio.atlassian.net/browse/GREEN-51797
> GREEN-51797: Developer resources - replace 'web hook' with webhook

- source/layouts/layout.erb
- source/stylesheets/screen_assessment.css.scss
- source/stylesheets/screen_audit-log.css.scss
- source/stylesheets/screen_candidate-ingestion.css.scss
- source/stylesheets/screen_gho.css.scss
- source/stylesheets/screen_harvest.css.scss
- source/stylesheets/screen_job-board.css.scss
- source/stylesheets/screen_webhooks.css.scss
https://greenhouseio.atlassian.net/browse/ON-6740
> ON-6740 resolve api documentation side menu visual bug

- source/includes/audit-log/_introduction.md
> 📝 GREEN-52657: Fix auditlog pagination docs

- source/includes/assessment/_introduction.md
- source/includes/assessment/_send_test.md
[JIRA CARD](https://greenhouseio.atlassian.net/browse/GREEN-53552)
> Update Assessment API response for send test to include preferred name

- source/includes/job-board/_applications.md
> Add applicant_ip param to POST for applications
